services:
    delorian.timetravel:
        class:  Oktolab\DelorianBundle\Model\TimetravelService
        arguments: [ @doctrine.orm.flow_entity_manager, @doctrine.orm.delorian_entity_manager, %bprs_asset.adapters%, @bprs_jobservice, %oktolab_media.episode_class%, %oktolab_media.series_class%, %oktolab_media.asset_class%, %bprs_worker_queue%, @guzzle.client ]
