imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            #- 'bootstrap_3_layout.html.twig'
            - 'BprsStyleBundle:Form:fields.html.twig'
    globals:
        name:         "DELORIAN"
        version:      "Alpha"
        junksize:     "%bprs_asset.junksize%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: delorian
        connections:
            flow:
                driver:   "%database_driver%"
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  utf8
            delorian:
                driver: pdo_sqlite
                path: "%kernel.root_dir%/delorian.db3"
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        # auto_mapping: true
        default_entity_manager: delorian
        entity_managers:
            flow:
                connection: flow
                mappings:
                    OktolabDelorianBundle: ~
            delorian:
                connection: delorian
                mappings:
                    OktolabMediaBundle: ~
                    BprsAssetBundle: ~
                    BprsAppLinkBundle: ~
                    AppBundle: ~
                    BprsUserBundle: ~
                    MediaBundle: ~
        resolve_target_entities:
            Bprs\AssetBundle\Entity\AssetInterface: AppBundle\Entity\Asset
            Oktolab\MediaBundle\Entity\EpisodeInterface: Okto\MediaBundle\Entity\Episode

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

services:
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false

oktolab_media:
    episode_class: "Okto\MediaBundle\Entity\Episode"
    series_class: "Okto\MediaBundle\Entity\Series"
    asset_class: "AppBundle\Entity\Asset"
    encoding_filesystem: cache
    resolutions:
        720p:
            name: 720p
            sortNumber: 1
            video_width: 1280
            video_height: 720
        1080p:
            name: 1080p
            sortNumber: 2
            video_width: 1920
            video_height: 1080
        360p:
            name: 360p
            sortNumber: 0
            video_width: 480
            video_height: 360
        facebook:
            name: facebook
            sortNumber: -1
            video_width: 480
            video_height: 360
            container: mp4

jms_serializer:
    metadata:
            directories:
                OKTOLAB:
                    namespace_prefix: "Oktolab\MediaBundle"
                    path: "@OktolabMediaBundle/Resources/serializer/OKTOLAB"
                OKTO:
                    namespace_prefix: "Okto\MediaBundle"
                    path: "@MediaBundle/Resources/serializer/OKTO"

bprs_command_line:
    php_path: %php_path%
    worker_queue: %worker_queue%
    redis_backend: "%redis_backend%"

bprs_asset:
    class:  "AppBundle\Entity\Asset"
    filesystem_map: oneup_flysystem.mount_manager
    worker_queue: %worker_queue%
    adapters:
        lta_lager:
            path: "/Volumes/Share 1/LTA Lager"
        lta_v2:
            path: "/Volumes/LTAv1/LTAv2"
        posterframe:
            url:  "http://localhost/DELORIAN/web/uploads/posterframes"
            path: "/usr/local/var/www/htdocs/DELORIAN/web/uploads/posterframes"
        video:
            url:  "http://localhost/DELORIAN/web/uploads/videos"
            path: "/usr/local/var/www/htdocs/DELORIAN/web/uploads/videos"
        cache:
            url: "/tmp"
            path: "/tmp"

oneup_flysystem:
    adapters:
        posterframe:
            local:
                directory: %kernel.root_dir%/../web/uploads/posterframes
        video:
            local:
                directory: %kernel.root_dir%/../web/uploads/videos
        cache:
            local:
                directory: /tmp

    filesystems:
        posterframe:
            adapter: posterframe
            mount: posterframe
        video:
            adapter: video
            mount: video
        cache:
            adapter: cache
            mount: cache

oneup_uploader:
    chunks:
        maxage: 86400
        storage:
            directory: %kernel.cache_dir%/uploader/chunks
    mappings:
        posterframe:
            frontend: blueimp
            storage:
                type: flysystem
                filesystem: oneup_flysystem.posterframe_filesystem
        video:
            frontend: blueimp
            storage:
                type: flysystem
                filesystem: oneup_flysystem.video_filesystem

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig   # sliding pagination controls template
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig # sort link template

bprs_user:
    class: "AppBundle\\Entity\\User"
    mail:
        commandline_host:   %commandline_host% #www.yourhost.com
        adress:             %email_adress% #yourbot@example.com
        name:               %bot_name% #yourbot
