bprs_logbook:
    resource: "@BprsLogbookBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale:  de|en
    defaults: { _locale: de }

delorian:
    resource: "@OktolabDelorianBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}
    requirements:
        _locale:  de|en
    defaults: { _locale: de }


oktolab_media:
    resource: .
    type: oktolab_media

bprs_applink:
    resource: "@BprsAppLinkBundle/Controller/"
    type:     annotation
    prefix:   /

bprs_user:
    resource: .
    type: bprs_user

bprs_asset:
    resource: .
    type: bprs_asset
    # prefix:   /{_locale}
    # requirements:
    #     _locale:  de|en
    # defaults: { _locale: de }

oneup_uploader:
    resource: .
    type: uploader

bprs_commandline:
    resource: .
    type:   bprs_commandline
