security:
    role_hierarchy:
            ROLE_ADMIN: ROLE_USER

    encoders:
        Bprs\AppLinkBundle\Entity\Keychain: plaintext
        Bprs\UserBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    providers:
        database:
            entity:
                class: AppBundle:User
                property: username

        bprs_applink:
            entity:
                class: BprsAppLinkBundle:Keychain
                property: user
                manager_name: delorian

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        bprs_applink:
            pattern:  /api
            http_basic: ~
            anonymous: ~
            provider: bprs_applink
            stateless: true

        main:
            form_login:
                login_path: bprs_user_login
                check_path: bprs_user_login_check
                default_target_path: list_series
                csrf_token_generator: security.csrf.token_manager #csrf_provider: security.csrf.token_manager
            logout:
                path: bprs_user_logout
                target: /de
            anonymous: ~
            logout_on_user_change: true
            provider: database
            remember_me:
                secret: '%secret%'
                httponly: false
                secure: '%secure_cookie%'

    access_control:
        - { path: /login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: /, roles: ROLE_USER }
        - { path: /backend/admin, roles: ROLE_ADMIN }
