services:
    oktolab.filebasedImportCommand:
        class:      AppBundle\Command\FilebasedImportCommand
        arguments: []
        tags:
            -  { name: console.command }

    oktolab.ReimportCommand:
        class:      AppBundle\Command\ReimportCommand
        arguments: []
        tags:
            -  { name: console.command }

    # TWIG Extension
    delorian.twig_extension:
        class: AppBundle\Twig\PTHelper
        public: false
        arguments:  [ "@doctrine.orm.flow_entity_manager" ]
        tags:
            - { name: twig.extension }

    AppBundle\Form\SeriesImportProgressType:
        arguments: [ "@translator" ]
        tags:
            - { name: form.type }
